=====================================
# Step 1: Import Required Libraries
=====================================

Import the necessary Python libraries for data manipulation,
data visualization, and handling date and time operations.

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from zoneinfo import ZoneInfo

=====================================
# Step 2: Load the Datasets
=====================================

Load the Google Play Store dataset and the User Reviews dataset into
Pandas DataFrames for further analysis.

In [16]:
play_store_data = pd.read_csv(
    r"C:\Users\Vansh Sharma\Downloads\Play Store Data (1).csv"
)

review = pd.read_csv(
    r"C:\Users\Vansh Sharma\Downloads\User Reviews (1).csv"
)

# Display first five rows
play_store_data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

=====================================
# Step 3: Explore the Datasets
=====================================

Understand the structure of both datasets by checking their dimensions,
data types, missing values, and summary information.

In [17]:
print("Play Store Dataset Shape :", play_store_data.shape)
print("User Reviews Dataset Shape :", review.shape)

print("\nPlay Store Dataset Info")
play_store_data.info()

print("\nUser Reviews Dataset Info")
review.info()

Play Store Dataset Shape : (10841, 13)
User Reviews Dataset Shape : (64295, 5)

Play Store Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

User Reviews Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  object
 1   Translated_Review       37427 non-null  object
 2   Sentiment               37432 non-null  object
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB

=====================================
# Step 4: Clean the Play Store Dataset
=====================================

Clean the Play Store dataset by removing duplicate records,
handling missing values, and converting important columns
to appropriate data types.

In [18]:
# Remove duplicate apps
play_store_data = play_store_data.drop_duplicates(subset='App')

# Convert Rating
play_store_data['Rating'] = pd.to_numeric(
    play_store_data['Rating'],
    errors='coerce'
)

# Convert Reviews
play_store_data['Reviews'] = pd.to_numeric(
    play_store_data['Reviews'],
    errors='coerce'
)

# Clean Installs
play_store_data['Installs'] = (
    play_store_data['Installs']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('+', '', regex=False)
)

play_store_data['Installs'] = pd.to_numeric(
    play_store_data['Installs'],
    errors='coerce'
)

# Clean Price
play_store_data['Price'] = (
    play_store_data['Price']
    .astype(str)
    .str.replace('$', '', regex=False)
)

play_store_data['Price'] = pd.to_numeric(
    play_store_data['Price'],
    errors='coerce'
)

=====================================
# Step 5: Convert App Size into MB
=====================================

Convert the Size column into numerical values (MB)
to make it suitable for visualization and analysis.

In [19]:
def convert_size(size):

    if pd.isna(size):
        return np.nan

    size = str(size)

    if size.endswith("M"):
        return float(size[:-1])

    elif size.endswith("k"):
        return float(size[:-1]) / 1024

    else:
        return np.nan


play_store_data["Size_MB"] = play_store_data["Size"].apply(convert_size)

play_store_data = play_store_data.dropna(
    subset=["Rating", "Reviews", "Installs", "Size_MB"]
)

play_store_data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_MB
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,10000.0,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,19.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,8.7
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,50000000.0,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,25.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2.8

=====================================
# Step 6: Clean the User Reviews Dataset
=====================================

Clean the User Reviews dataset by converting the
Sentiment Subjectivity column into numeric format,
removing missing values, and preparing the data
for merging.

In [20]:
# Keep only the required columns
review = review[['App', 'Sentiment_Subjectivity']]

# Convert Sentiment_Subjectivity to numeric
review['Sentiment_Subjectivity'] = pd.to_numeric(
    review['Sentiment_Subjectivity'],
    errors='coerce'
)

# Remove missing values
review = review.dropna(subset=['Sentiment_Subjectivity'])

# If an app has multiple reviews, calculate the average subjectivity
review = review.groupby('App', as_index=False)['Sentiment_Subjectivity'].mean()

print("User Reviews Dataset Shape:", review.shape)

review.head()

User Reviews Dataset Shape: (865, 2)

                                App  Sentiment_Subjectivity
0             10 Best Foods for You                0.495455
1  104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室                0.545516
2                              11st                0.443957
3        1800 Contacts - Lens Store                0.591098
4   1LINE – One Line with One Touch                0.557315

=====================================
# Step 7: Merge the Datasets
=====================================

Merge the Play Store dataset with the User Reviews
dataset using the App column. This allows us to
combine app information with sentiment subjectivity.

In [21]:
merged_data = pd.merge(
    play_store_data,
    review,
    on='App',
    how='inner'
)

print("Merged Dataset Shape:", merged_data.shape)

merged_data.head()

Merged Dataset Shape: (568, 15)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_MB,Sentiment_Subjectivity
0,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,14.0,0.641540
1,Garden Coloring Book,ART_AND_DESIGN,4.4,13791.0,33M,1000000.0,Free,0.0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up,33.0,0.523447
2,FlipaClip - Cartoon animation,ART_AND_DESIGN,4.3,194216.0,39M,5000000.0,Free,0.0,Everyone,Art & Design,"August 3, 2018",2.2.5,4.0.3 and up,39.0,0.679226
3,Boys Photo Editor - Six Pack & Men's Suit,ART_AND_DESIGN,4.1,654.0,12M,100000.0,Free,0.0,Everyone,Art & Design,"March 20, 2018",1.1,4.0.3 and up,12.0,0.479298
4,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260.0,25M,500000.0,Free,0.0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up,25.0,0.572762

=====================================
# Step 8: Apply Business Requirements
=====================================

Filter the merged dataset according to the given
business requirements.

Conditions:

• Rating > 3.5

• Reviews > 500

• Installs > 50,000

• Sentiment Subjectivity > 0.5

• App name should not contain the letter 'S'

• Categories:
  - Game
  - Beauty
  - Business
  - Comics
  - Communication
  - Dating
  - Entertainment
  - Social
  - Events

In [22]:
# Required Categories
required_categories = [
    'GAME',
    'BEAUTY',
    'BUSINESS',
    'COMICS',
    'COMMUNICATION',
    'DATING',
    'ENTERTAINMENT',
    'SOCIAL',
    'EVENTS'
]

# Apply all filters
filtered_data = merged_data[
    (merged_data['Rating'] > 3.5) &
    (merged_data['Reviews'] > 500) &
    (merged_data['Installs'] > 50000) &
    (merged_data['Sentiment_Subjectivity'] > 0.5) &
    (~merged_data['App'].str.contains('S', case=False, na=False)) &
    (merged_data['Category'].isin(required_categories))
].copy()

print("Filtered Dataset Shape:", filtered_data.shape)

filtered_data.head()

Filtered Dataset Shape: (23, 15)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_MB,Sentiment_Subjectivity
30,Google Primer,BUSINESS,4.4,62272.0,18M,10000000.0,Free,0.0,Everyone,Business,"June 26, 2018",3.550.2,4.1 and up,18.000000,0.675000
31,Call Blocker,BUSINESS,4.6,188841.0,3.2M,5000000.0,Free,0.0,Everyone,Business,"June 21, 2018",1.1.13,4.0 and up,3.200000,0.655431
54,"CallApp: Caller ID, Blocker & Phone Call Recorder",COMMUNICATION,4.4,483565.0,20M,10000000.0,Free,0.0,Everyone,Communication,"July 29, 2018",1.286,4.1 and up,20.000000,0.506481
56,Caller ID +,COMMUNICATION,4.0,9498.0,118k,1000000.0,Free,0.0,Everyone,Communication,"June 7, 2016",5.28.0,2.3 and up,0.115234,0.600000
59,"Hily: Dating, Chat, Match, Meet & Hook up",DATING,4.1,2556.0,56M,100000.0,Free,0.0,Mature 17+,Dating,"August 1, 2018",2.5.2,4.1 and up,56.000000,0.555331

In [23]:
print(sorted(merged_data['Category'].unique()))

['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY', 'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION', 'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FAMILY', 'FINANCE', 'FOOD_AND_DRINK', 'GAME', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME', 'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'MAPS_AND_NAVIGATION', 'MEDICAL', 'NEWS_AND_MAGAZINES', 'PARENTING', 'PERSONALIZATION', 'PHOTOGRAPHY', 'PRODUCTIVITY', 'SHOPPING', 'SOCIAL', 'SPORTS', 'TOOLS', 'TRAVEL_AND_LOCAL', 'VIDEO_PLAYERS', 'WEATHER']

=====================================
# Step 9: Translate Category Names
=====================================

Translate selected category names for visualization purposes only.

Translations:

• Beauty → सौंदर्य (Hindi)

• Business → வணிகம் (Tamil)

• Dating → Partnersuche (German)

The original dataset remains unchanged.

In [24]:
# Translate category names only for display
category_translation = {
    'BEAUTY': 'सौंदर्य',
    'BUSINESS': 'வணிகம்',
    'DATING': 'Partnersuche'
}

filtered_data['Category_Display'] = (
    filtered_data['Category']
    .replace(category_translation)
)

filtered_data[['Category', 'Category_Display']].drop_duplicates()

          Category Category_Display
30        BUSINESS           வணிகம்
54   COMMUNICATION    COMMUNICATION
59          DATING     Partnersuche
105  ENTERTAINMENT    ENTERTAINMENT
237           GAME             GAME
363         SOCIAL           SOCIAL

=====================================
# Step 10: Check Time Constraint (IST)
=====================================

Verify the current Indian Standard Time (IST).

The Bubble Chart will be displayed only if the
current time is between **5:00 PM IST** and **7:00 PM IST**.
Otherwise, a message will be displayed.

In [25]:
# Get current IST time
current_time = datetime.now(ZoneInfo("Asia/Kolkata")).time()

# Define allowed time
start_time = datetime.strptime("17:00", "%H:%M").time()
end_time = datetime.strptime("19:00", "%H:%M").time()

print("Current IST Time :", current_time)

Current IST Time : 22:50:27.063967

=====================================
# Step 11: Plot the Bubble Chart
=====================================

Create a Bubble Chart to visualize the relationship
between App Size (MB) and App Rating.

Chart Details:

• X-axis → App Size (MB)

• Y-axis → App Rating

• Bubble Size → Number of Installs

• Bubble Color → Category

• Game Category highlighted in Pink

• Beauty, Business and Dating displayed in translated languages.

In [26]:
if start_time <= current_time <= end_time:

    plt.figure(figsize=(15,8))

    # Category colors
    colors = {
        'GAME': 'pink',
        'सौंदर्य': 'gold',
        'வணிகம்': 'green',
        'COMICS': 'orange',
        'COMMUNICATION': 'blue',
        'Partnersuche': 'red',
        'ENTERTAINMENT': 'purple',
        'SOCIAL': 'cyan',
        'EVENTS': 'gray'
    }

    for category in filtered_data['Category_Display'].unique():

        temp = filtered_data[
            filtered_data['Category_Display'] == category
        ]

        original_category = temp['Category'].iloc[0]

        if original_category == "GAME":
            color = "pink"
        else:
            color = colors.get(category, "black")

        plt.scatter(
            x=temp["Size_MB"],
            y=temp["Rating"],
            s=temp["Installs"]/1000,
            c=color,
            alpha=0.7,
            edgecolors="black",
            linewidth=0.5,
            label=category
        )

    plt.title(
        "Bubble Chart: App Size vs Rating",
        fontsize=16,
        fontweight="bold"
    )

    plt.xlabel("App Size (MB)", fontsize=12)

    plt.ylabel("Average Rating", fontsize=12)

    plt.grid(True, linestyle="--", alpha=0.5)

    plt.legend(title="Category")

    plt.tight_layout()

    plt.show()

else:

    print("Bubble chart is available only between 5 PM IST and 7 PM IST.")

Bubble chart is available only between 5 PM IST and 7 PM IST.

=====================================
# Step 12: Conclusion
=====================================

The Bubble Chart visualizes the relationship between
App Size and App Rating, with bubble size representing
the number of installs.

All specified business requirements were successfully
implemented, including category filtering, sentiment
filtering, app name filtering, translated category labels,
customized colors, and the time-based display restriction.

In [27]:
print(filtered_data['Category'].unique())

['BUSINESS' 'COMMUNICATION' 'DATING' 'ENTERTAINMENT' 'GAME' 'SOCIAL']